import type { LevelDefinition } from "../types";

/**
 * Fase 1 — roteiro do briefing v2 (seção 6).
 *
 * `satireText` e as frases de apresentação são redação do jogo (ficção).
 * `sourcedSummary` são resumos próprios das fontes S01–S06 e S15; continuam
 * `pending` até serem conferidos contra o texto das fontes.
 */
export const triplexLevel: LevelDefinition = {
  id: "triplex",
  number: 1,
  title: "Tríplex: Subindo na Vida",
  subtitle: "Guarujá — a controvérsia que virou processo",
  summary:
    "Um prédio à beira-mar, um empreiteiro da OAS, uma reforma sob medida e um elevador privativo. Suba pela controvérsia e encontre as versões da acusação, da defesa e das decisões.",
  mechanic: "platformer",
  implementationStatus: "playable",
  editorialStatus: "pending",
  objective: "Cumpra as seis missões da subida e saia pelo terraço.",
  intro:
    "Um prédio à beira-mar. Uma reforma sob medida. E uma pergunta que não cabe no elevador: quem ficou com a conta?",
  factualLine: {
    text: "A acusação noticiada relacionava benefícios da OAS a contratos da Petrobras. Lula negou recebimento ilícito; as condenações foram anuladas.",
    sourceIds: ["S01", "S03"],
  },
  fictionalizationNote:
    "O empreiteiro é um personagem genérico criado para o jogo; as falas dele não são de Léo Pinheiro nem de outra pessoa real. O contrato é uma ilustração e não reproduz documento real. A mala é uma metáfora da vantagem alegada pela acusação: as fontes não relatam uma entrega de dinheiro neste episódio. Missões, frases cômicas e animações foram criadas para o jogo. Os carimbos resumem decisões na ordem em que aconteceram; anulação, suspeição e prescrição não decidem o mérito das acusações.",
  sourceIds: ["S01", "S02", "S15", "S03", "S04", "S05", "S06"],
  narrativeEvents: [
    {
      id: "meet-contractor",
      missionTitle: "Procure o empreiteiro da OAS",
      hudObjective: "Procure o empreiteiro da OAS no tapume.",
      trigger: "interact",
      objectKind: "npc",
      objectLabel: "Empreiteiro",
      satireText: "Por aqui, a conversa começa na planta e termina no processo.",
      sourcedSummary:
        "Léo Pinheiro afirmou em depoimento que a unidade estava reservada à família de Lula. A defesa contestou a versão.",
      attributionLabel: "Relato de Léo Pinheiro • UOL • 20/04/2017",
      category: "allegation",
      sourceIds: ["S02"],
      fictionNote: "O empreiteiro é um personagem fictício. A fala não é de Léo Pinheiro.",
      required: true,
      nextEventId: "find-contract",
    },
    {
      id: "find-contract",
      missionTitle: "Encontre o contrato da Petrobras",
      hudObjective: "Encontre o contrato na mesa.",
      trigger: "interact",
      objectKind: "contract",
      objectLabel: "Contratos Petrobras",
      satireText: "A pasta é grande. A pergunta também.",
      sourcedSummary: "O MPF alegou ligação entre vantagens da OAS e favorecimento em contratos da Petrobras.",
      attributionLabel: "Segundo o MPF • Agência Brasil • 24/01/2018",
      category: "allegation",
      sourceIds: ["S01"],
      fictionNote: "Ilustração — não reproduz um contrato real. A pasta representa a relação alegada; não prova que Lula assinou contratos da estatal.",
      required: true,
      nextEventId: "assemble-renovation",
    },
    {
      id: "assemble-renovation",
      missionTitle: "Ache a planta da reforma",
      hudObjective: "Ache as três peças da planta da reforma.",
      trigger: "collect",
      objectKind: "blueprint",
      objectLabel: "Planta da reforma",
      satireText: "A reforma sobe de padrão. O caso sobe de instância.",
      sourcedSummary:
        "Executivos da OAS relataram obras e um elevador privativo; um deles disse que a empresa bancou a reforma. A defesa contestou o benefício atribuído a Lula.",
      attributionLabel: "Relatos de executivos da OAS • Folha • 26/04/2017",
      category: "allegation",
      sourceIds: ["S15"],
      fictionNote: "A planta é cenográfica. A transformação do cenário não define titularidade nem ilicitude.",
      required: true,
      nextEventId: "symbolic-bag",
    },
    {
      id: "symbolic-bag",
      missionTitle: "Encontre a mala de dinheiro",
      hudObjective: "Encontre a mala de dinheiro.",
      trigger: "interact",
      objectKind: "symbolic_bag",
      objectLabel: "METÁFORA DA ACUSAÇÃO",
      satireText: "Neste jogo, a acusação ganhou alça.",
      sourcedSummary:
        "A mala representa a vantagem indevida alegada. Não retrata uma entrega literal noticiada neste episódio.",
      attributionLabel: "Metáfora do jogo • tese da acusação: Agência Brasil • 24/01/2018",
      category: "metaphor",
      sourceIds: ["S01"],
      fictionNote: "A mala é uma metáfora visual. A fonte associada trata da tese sobre vantagem e não é evidência de uma mala real.",
      required: true,
      nextEventId: "private-elevator",
    },
    {
      id: "private-elevator",
      missionTitle: "Use o elevador privativo",
      hudObjective: "Use o elevador privativo.",
      trigger: "proximity",
      objectKind: "elevator",
      objectLabel: "Privativo",
      satireText: "Subir ficou fácil. Explicar a subida, nem tanto.",
      sourcedSummary: "O elevador privativo aparece nos relatos sobre a reforma do tríplex.",
      attributionLabel: "Relatos noticiados • UOL 20/04/2017 • Folha 26/04/2017",
      category: "news",
      sourceIds: ["S02", "S15"],
      required: true,
      nextEventId: "open-defense",
    },
    {
      id: "open-defense",
      missionTitle: "Abra a versão da defesa",
      hudObjective: "Abra a versão da defesa.",
      trigger: "interact",
      objectKind: "defense_card",
      objectLabel: "Defesa de Lula",
      satireText: "Na escritura e no processo, a história tem versões diferentes.",
      sourcedSummary:
        "Lula negou ser proprietário do tríplex e receber vantagem ilícita. Sua defesa contestou o relato de Pinheiro e a prova de benefício pessoal.",
      attributionLabel: "Defesa de Lula • UOL • 20/04/2017",
      category: "defense",
      sourceIds: ["S02"],
      required: true,
    },
  ],
  outcomes: [
    { id: "out-2017", year: "2017", headline: "HOUVE CONDENAÇÃO", detail: "A decisão seria posteriormente anulada.", sourceIds: ["S01"] },
    { id: "out-2021-a", year: "2021", headline: "CONDENAÇÕES ANULADAS", detail: "Incompetência da vara de Curitiba.", sourceIds: ["S03"] },
    {
      id: "out-2021-b",
      year: "2021",
      headline: "JUIZ CONSIDERADO PARCIAL",
      detail: "STF confirmou a suspeição de Sergio Moro no caso do tríplex.",
      sourceIds: ["S04"],
    },
    {
      id: "out-2022",
      year: "2022",
      headline: "CASO ARQUIVADO",
      detail: "Extinção da punibilidade por prescrição quanto às imputações do tríplex.",
      sourceIds: ["S05", "S06"],
    },
  ],
  finalJoke: "O prédio tinha três andares. A história ganhou outros capítulos.",
  claims: [
    {
      id: "triplex-acusacao",
      category: "allegation",
      text: "A reforma e o apartamento foram apresentados pela acusação como benefícios relacionados à OAS.",
      attribution: "Ministério Público Federal, segundo a Agência Brasil (24/01/2018)",
      sourceIds: ["S01"],
      status: "pending",
    },
    {
      id: "triplex-relatos",
      category: "allegation",
      text: "Léo Pinheiro e outros executivos da OAS deram versões sobre a reserva do apartamento e as reformas; a defesa as contestou.",
      attribution: "Depoimentos noticiados em abril de 2017 (UOL e Folha)",
      sourceIds: ["S02", "S15"],
      status: "pending",
    },
    {
      id: "triplex-defesa",
      category: "defense",
      text: "Lula negou ser proprietário do tríplex e ter recebido vantagem ilícita.",
      attribution: "Defesa de Lula, segundo o UOL (20/04/2017)",
      sourceIds: ["S02"],
      status: "pending",
    },
    {
      id: "triplex-condenacao",
      category: "legal_outcome",
      text: "Em 2017, houve condenação no caso. A decisão foi posteriormente anulada.",
      sourceIds: ["S01"],
      status: "pending",
    },
    {
      id: "triplex-anulacao",
      category: "legal_outcome",
      text: "Em 2021, o STF manteve a anulação das condenações por incompetência da vara de Curitiba.",
      sourceIds: ["S03"],
      status: "pending",
    },
    {
      id: "triplex-suspeicao",
      category: "legal_outcome",
      text: "Em 2021, o STF confirmou a suspeição de Sergio Moro na ação do tríplex.",
      sourceIds: ["S04"],
      status: "pending",
    },
    {
      id: "triplex-arquivamento",
      category: "legal_outcome",
      text: "Em janeiro de 2022, a Justiça Federal do DF arquivou o processo quanto às imputações do tríplex, por prescrição.",
      sourceIds: ["S05", "S06"],
      status: "pending",
    },
  ],
};
