import type { Source } from "../types";

/**
 * Registro de fontes (briefing v2, seção 9).
 *
 * O briefing v2 informa que estas fontes foram consultadas em 07/10/2026.
 * Elas continuam `pending` aqui porque ninguém conferiu, neste repositório,
 * os resumos do jogo contra o texto das fontes: o ambiente em que o código
 * foi escrito não tinha acesso a esses sites. Para revisar, ver
 * docs/editorial-review.md.
 */
const BRIEFING_NOTE =
  "Consultada pelo briefing v2 em 07/10/2026. Não lida no ambiente de desenvolvimento (acesso bloqueado). Conferir o resumo do jogo contra o texto antes de marcar como revisada.";

export const sources: Source[] = [
  {
    id: "S01",
    title: "Entenda o caso triplex em que Lula foi condenado",
    publisher: "Agência Brasil",
    author: "Paulo Victor Chagas",
    url: "https://agenciabrasil.ebc.com.br/politica/noticia/2018-01/entenda-o-caso-triplex-em-que-lula-foi-condenado",
    publishedAt: "2018-01-24",
    status: "pending",
    scope:
      "Tese acusatória, ligação alegada com contratos da Petrobras, defesa e condenação histórica. Notícia da época: acompanhar de S03–S06. Não sustenta entrega literal de mala.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S02",
    title: "Tríplex do Guarujá era de Lula, diz Léo Pinheiro a Moro na Lava Jato",
    publisher: "UOL Notícias",
    author: "Andressa Rovani, Bernardo Barbosa, Daniela Garcia e Gustavo Maia",
    url: "https://noticias.uol.com.br/politica/ultimas-noticias/2017/04/20/tinha-orientacao-para-nao-colocar-a-venda-porque-era-da-familia-de-lula-diz-leo-pinheiro-sobre-triplex.amp.htm",
    publishedAt: "2017-04-20",
    status: "pending",
    scope:
      "Versão de Pinheiro sobre reserva e obras; negativa da defesa. Relato atribuído ao depoente, não certificação de titularidade pelo jornal. Atualizada em 24/04/2017.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S03",
    title: "STF mantém anulação das condenações de Lula",
    publisher: "Agência Brasil",
    author: "André Richter",
    url: "https://agenciabrasil.ebc.com.br/justica/noticia/2021-04/stf-mantem-anulacao-das-condenacoes-de-lula",
    publishedAt: "2021-04-15",
    status: "pending",
    accessMode: "search_content",
    scope: "Decisão sobre competência, anulações e efeito sobre elegibilidade. Não houve leitura do acórdão completo.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S04",
    title: "STF confirma suspeição de Sergio Moro na ação do triplex do Guarujá",
    publisher: "Supremo Tribunal Federal",
    url: "https://portal.stf.jus.br/noticias/verNoticiaDetalhe.asp?idConteudo=468086&ori=1",
    publishedAt: "2021-06-23",
    status: "pending",
    accessMode: "search_content",
    scope: "Confirmação da suspeição e manutenção da anulação de atos no caso.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S05",
    title: "Juíza do DF arquiva processo contra Lula no caso do tríplex do Guarujá",
    publisher: "Migalhas",
    author: "Redação",
    url: "https://www.migalhas.com.br/quentes/358845/juiza-do-df-arquiva-processo-contra-lula-no-caso-do-triplex-do-guaruja",
    publishedAt: "2022-01-28",
    status: "pending",
    scope: "Encerramento por prescrição quanto às imputações relativas ao tríplex. Conferência complementar: S06.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S06",
    title: "Decisão de arquivamento — 12ª Vara Federal Criminal do DF (cópia pública)",
    publisher: "Justiça Federal do DF, via Migalhas",
    url: "https://www.migalhas.com.br/arquivos/2022/1/A1321D59CAC7E2_acao.pdf",
    publishedAt: "2022-01-27",
    status: "pending",
    accessMode: "document",
    scope:
      "Processos 1070239-94.2021.4.01.3400 e 1028899-73.2021.4.01.3400. Dispositivo de arquivamento por prescrição quanto ao tríplex. Não confundir com os capítulos sobre o acervo presidencial.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S07",
    title: "Lava Jato: MPF apresenta nova denúncia contra Lula envolvendo o sítio de Atibaia",
    publisher: "Agência Brasil, reproduzida pelo UOL",
    author: "Ivan Richard Esposito",
    url: "https://noticias.uol.com.br/ultimas-noticias/agencia-brasil/2017/05/22/lava-jato-mpf-apresenta-nova-denuncia-contra-lula-envolvendo-o-sitio-de-atibaia.htm",
    publishedAt: "2017-05-22",
    status: "pending",
    scope: "Tese sobre reformas e resposta defensiva. Valores e relações da acusação não são corrupção confirmada.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S08",
    title: "Juíza de Brasília rejeita denúncia contra Lula no caso do sítio de Atibaia",
    publisher: "CNN Brasil",
    author: "João de Mari",
    url: "https://www.cnnbrasil.com.br/politica/juiza-de-brasilia-rejeita-denuncia-contra-lula-sobre-sitio-de-atibaia/",
    publishedAt: "2021-08-22",
    status: "pending",
    scope: "Rejeição, fundamentos noticiados e posição da defesa. Não generalizar para outros casos.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S09",
    title: "Investigação sobre negócios de filho de Lula é arquivada",
    publisher: "Folha de S.Paulo",
    author: "José Ernesto Credendio e Andreza Matais",
    url: "https://www1.folha.uol.com.br/fsp/poder/76983-investigacao-sobre-negocios-de-filho-de-lula-e-arquivada.shtml",
    publishedAt: "2012-11-09",
    status: "pending",
    scope: "Investimento noticiado, expressão sobre o talento empresarial do filho e arquivamento. Não confundir com o inquérito encerrado em 2022.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S10",
    title: "Justiça arquiva caso que liga Lulinha a supostos repasses ilegais da Oi",
    publisher: "Folha de S.Paulo",
    author: "Mônica Bergamo",
    url: "https://www1.folha.uol.com.br/amp/colunas/monicabergamo/2022/01/justica-arquiva-caso-que-liga-lulinha-a-supostos-repasses-ilegais-da-oi.shtml",
    publishedAt: "2022-01-17",
    status: "pending",
    scope: "Pedido do MPF, exclusão de provas e arquivamento. Não apresentar como investigação ativa.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S11",
    title: "Com 47 votos favoráveis, Senado aprova Dino para o STF",
    publisher: "Agência Senado",
    author: "Rodrigo Baptista",
    url: "https://www12.senado.leg.br/noticias/materias/2023/12/13/com-47-votos-favoraveis-senado-aprova-dino-para-o-stf",
    publishedAt: "2023-12-13",
    status: "pending",
    scope: "Trajetória, aprovação e declaração de Dino sobre atuação sem viés político. Críticas na sabatina são opiniões de parlamentares.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S12",
    title: "Posse de Flávio Dino no STF",
    publisher: "Supremo Tribunal Federal",
    url: "https://portal.stf.jus.br/noticias/verNoticiaDetalhe.asp?idConteudo=527684",
    publishedAt: "2024-02-22",
    status: "pending",
    accessMode: "search_content",
    scope: "Indicação por Lula e posse na vaga de Rosa Weber.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S13",
    title: "Eleições presidenciais — 2006",
    publisher: "Memória Globo",
    url: "https://memoriaglobo.globo.com/jornalismo/coberturas/eleicoes-presidenciais-2006/noticia/eleicoes-presidenciais-2006.ghtml",
    status: "pending",
    scope: "Ausência no debate de setembro e participação em outubro de 2006. Não trasladar para 2026.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S14",
    title: "Comício em São Bernardo na noite do debate (Folha, 29/09/2006)",
    publisher: "Folha de S.Paulo",
    url: "https://www1.folha.uol.com.br/fsp/brasil/fc2909200606.htm",
    publishedAt: "2006-09-29",
    status: "pending",
    scope: "Presença em comício na noite da ausência. O stealth do jogo é invenção.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S15",
    title: "Executivos dizem que reformaram tríplex para Lula a pedido de Pinheiro",
    publisher: "Folha de S.Paulo",
    author: "José Marques",
    url: "https://www1.folha.uol.com.br/poder/2017/04/1878950-executivos-dizem-que-reformaram-triplex-para-lula-a-pedido-de-pinheiro.shtml",
    publishedAt: "2017-04-26",
    status: "pending",
    accessMode: "search_content",
    scope: "Relatos sobre projeto, elevador e custeio; contestação defensiva.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S16",
    title: "Após decisão do STF, juiz manda soltar ex-presidente Lula",
    publisher: "Agência Brasil",
    url: "https://agenciabrasil.ebc.com.br/justica/noticia/2019-11/apos-decisao-do-stf-juiz-manda-soltar-ex-presidente-lula",
    publishedAt: "2019-11-08",
    status: "pending",
    accessMode: "search_content",
    scope: "Fundamento e data da determinação de soltura.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S17",
    title: "100% das seções totalizadas: confira como ficou o quadro eleitoral após o 2º turno",
    publisher: "Tribunal Superior Eleitoral",
    url: "https://www.tse.jus.br/comunicacao/noticias/2022/Outubro/100-das-secoes-totalizadas-confira-como-ficou-o-quadro-eleitoral-apos-o-2o-turno/",
    publishedAt: "2022-10-31",
    status: "pending",
    scope: "Eleição de Lula em 2022. Não usar para 2026.",
    notes: BRIEFING_NOTE,
  },
  {
    id: "S18",
    title: "Informativo 696 — REsp 1.729.550/SP (liberdade de crítica e diligência)",
    publisher: "Superior Tribunal de Justiça",
    url: "https://processo.stj.jus.br/jurisprudencia/externo/informativo/?acao=pesquisar&aplicacao=informativo&livre=%40CNOT%3D%27018151%27",
    publishedAt: "2021-05-14",
    status: "pending",
    scope: "Referência editorial interna. Não é validação jurídica do jogo nem garantia de ausência de responsabilidade.",
    notes: BRIEFING_NOTE,
  },
];

export const sourcesById: ReadonlyMap<string, Source> = new Map(sources.map((s) => [s.id, s]));
